In [1]:
import numpy as np
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [2]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [3]:
# accessing elements
arr_2d[0][1]     # 1. Double [] notation

10

In [4]:
arr_2d[0]

array([ 5, 10, 15])

In [7]:
arr_2d[1]

array([20, 25, 30])

In [8]:
# 2. Single [] notation
arr_2d[1,2]

30

In [9]:
# extracting the subarray
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d[0:,0]

array([ 5, 20, 35])

In [13]:
# 3. Condition selection
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr>5   # boolean array T/F value for each element of arr based on condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [15]:
bool_arr=arr>5   

In [16]:
arr[bool_arr]    # elements satisfying the conditions

array([ 6,  7,  8,  9, 10])

In [17]:
# In one step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [19]:
arr[arr%2] # making odd element as element at index 1 & even as element at index 2

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1])

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# 4. by using .arange and then reshaping
arr_2d=np.arange(50).reshape(5,10)

In [25]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr_2d[1:4,1:5]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])