In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Array with Array operation

In [4]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr + 2*arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Array with scalar Operation

In [8]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [11]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr-0.5

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [15]:
arr+100-50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [16]:
arr+100*0.5

array([51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [17]:
arr+50.0

array([51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [19]:
arr2=np.arange(0,6)

In [20]:
arr2

array([0, 1, 2, 3, 4, 5])

In [21]:
arr2/arr2  # warning for 0/0  , no interruption

C:\Users\HP\AppData\Local\Temp\ipykernel_22072\4263725751.py:1: RuntimeWarning: invalid value encountered in divide
  arr2/arr2


array([nan,  1.,  1.,  1.,  1.,  1.])

In [22]:
1/arr2                     # 1/0 -> infinity

C:\Users\HP\AppData\Local\Temp\ipykernel_22072\1672552411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [23]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Universal array function

In [24]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [25]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [26]:
np.max(arr)

10

In [27]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [29]:
np.log(arr2)    # log(0)= -infininty

C:\Users\HP\AppData\Local\Temp\ipykernel_22072\2430268246.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])