In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np


In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_2d=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr2d=np.array(my_2d)

In [11]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Builtin array

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# step size
a=np.arange(1,11,2)
b=np.arange(0,11,2)
b
a
# will print only once

array([1, 3, 5, 7, 9])

In [19]:
# alll zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# all 1's
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# to have evenly spaced points
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [27]:
np.linspace(1,10,200)

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [28]:
# range's 3rd arg. = step size you want
# linspace's 3rd arg.= no. of points you want

In [29]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# an array of random numbers
np.random.rand(5)   # outputs b/w 0 and 1

array([0.04233008, 0.47103144, 0.60105763, 0.53586405, 0.83390164])

In [31]:
np.random.rand(4,4)      # 2d

array([[0.0498105 , 0.5594931 , 0.94619313, 0.43133492],
       [0.6403046 , 0.81974447, 0.38389515, 0.29691634],
       [0.60076074, 0.57013413, 0.19757844, 0.22913498],
       [0.62809139, 0.85539962, 0.96527891, 0.88904113]])

In [32]:
# .rand -> uniform distr. from 0 to 1
#  .randn -> standard normal distr. around 0   i.e. -1 to 1
#             e.g. Gaussian distr. curve

In [34]:
# to select a random number between given range
np.random.randint(1,100)   # b/w 1 to 99 

26

In [36]:
np.random.randint(1,100,10)   # array containing 10 number of random numbers 

array([54, 28, 33, 96, 79, 63, 46, 32, 72, 18])

In [37]:
arr=np.arange(0,25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
# reshaping the array
arr.reshape(5,5)  # it should fill all elements of arr,otherwise give error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
# arr.reshape(2,4)         -> error

In [42]:
ranarr=np.random.randint(1,100,10)

In [43]:
ranarr

array([88, 47, 32, 19, 34, 56,  1, 14, 11, 79])

In [44]:
ranarr.max()    # max element value

88

In [45]:
ranarr.min()    # min element value

1

In [46]:
ranarr.argmax()  # index of max value

0

In [47]:
ranarr.argmin()   # index of min value

6

In [48]:
# shape of array
arr.shape

(25,)

In [49]:
ranarr.shape

(10,)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr=arr.reshape(5,5)
arr.shape

(5, 5)

In [52]:
arr.dtype  # datatype

dtype('int32')

In [59]:
# to have direct reference  of functions we have to import them
from numpy.random import randint as ri

ri(1,100)

74